setpoint: 0.0
mass: 1.0
k_linear: 1.0
k_nonlinear: 0.1
k_damping: 0.1

process_noise_std: 0.05
measurement_noise_std: 0.02

hidden_size: 64
num_layers: 2
input_size: 3
output_size: 3

seed: 42
device: 'cpu'
batch_size: 64
learning_rate: 1e-5
update_target_freq: 4
gamma: 0.9
target_update_eps: 0.995

frames_per_batch: 50
total_frames: -1
buffer_size: 10000
update_to_data: 16
max_train_steps: 2000

exploration_annealing_steps: 1000

qvalue_num_cells: 64
qvalue_depth: 2
qvalue_out_features: 1
num_qvalue_nets: 2