experiment_name: coefficient_scan

setpoint: 1200 # CHECK

serial: # CHECK
  port: COM3
  baudrate: 115200
  timeout: 0.1
  use_mock: false

hydra:
  run:
    dir: experiments/${experiment_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
