experiment_name: kp_scan

setpoint: 1200 # CHECK

serial: # CHECK
  port: COM3
  baudrate: 115200
  timeout: 0.1
  use_mock: false

kp_scan:
  num_points: 100  
  steps_per_kp_value: 200  

control_output_limits:
  default_min: 0
  default_max: 4095
  force_min_value: 2000
  force_max_value: 2500
  lower_force_condition_threshold: 200
  upper_force_condition_threshold: 4000
  enforcement_steps: 1000

hydra:
  run:
    dir: experiments/${experiment_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
