experiment_name: pid_grid_scan

setpoint: 1200 # CHECK

serial: # CHECK
  port: COM3
  baudrate: 115200
  timeout: 0.1

  use_mock: false

grid:
  num_points: 7
  steps_per_point: 2000

control_output_limits:
  default_min: 0.0
  default_max: 4095.0
  force_min_value: 2000.0
  force_max_value: 2500.0
  force_condition_threshold: 200.0
  enforcement_steps: 1000

hydra:
  run:
    dir: experiments/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

