experiment_name: td3_train_simulation
seed: 42 

defaults:
  - agent: agent
  - _self_

data:
  frames_per_batch: 200 # 1000 для "InvertedPendulum-v5" и "InvertedDoublePendulum-v5"; 200 для "Pendulum-v1" и "PendulumNoVel"
  total_frames: -1

  buffer_size: 100_000

env:
  name: "PendulumNoVel" # "InvertedPendulum-v5" "Pendulum-v1" "InvertedDoublePendulum-v5" "PendulumNoVel"

  # TODO убрать (необходимо для поддержки benchmark)
  setpoint: 1.0 # CHECK

  bounds:
    action:
      low: [0.0, 0.0, 0.0]
      high: [17.5, 55.0, 0.01]
    observation:
      low: [0.0, 0.0, 0.0]
      high: [10230.0, 4095.0, 10230.0]
    reward:
      low: [-10230.0]
      high: [0]

  mass: 1.0 # TODO: Убрать после решения проблемы с двойным созданием подключения
  k_linear: 1.0
  k_nonlinear: 1.0
  k_damping: 0.1

  process_noise_std: 0.05
  measurement_noise_std: 0.02

train:
  batch_size: 128
  
  update_to_data: ${data.frames_per_batch}
  update_actor_freq: 2

  total_train_steps: 1_000_000

hydra:
  run:
    dir: experiments/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}