experiment_name: td3_train_simulation_sync_recurrent
seed: 42 

hydra:
  run:
    dir: experiments/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

env:
  name: "Pendulum-v1"
  seed: 42
  num_episodes: 500
  num_steps: 200

agent:
  seq_len: 20
  batch_size: 64
  update_to_data: 16

  shared_summary: False

  mlp_hidden_size: 256
  rnn_hidden_size: 64
  num_rnn_layers: 2

  lr: 1e-3
  gamma: 0.99
  tau: 0.05
  policy_noise: 0.2
  noise_clip: 0.5
  policy_freq: 2

