experiment_name: td3_train_real
seed: 42 

serial: 
  port: COM15
  baudrate: 115200
  timeout: 0.1
  
hydra:
  run:
    dir: experiments/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  frames_per_batch: 50
  total_frames: -1

  buffer_size: 100_000

agent:
  lstm_hidden_size: 32
  lstm_num_layers: 1
  mlp_depth: 1
  mlp_num_cells: 32

  q_mlp_depth: 1
  q_mlp_num_cells: 32

  gamma: 0.99
  num_qvalue_nets: 2
  target_update_eps: 0.95

  learning_rate_actor: 1e-6
  learning_rate_critic: 1e-5

env:
  setpoint: 500.0

  bounds:
    action:
      low: [0.0, 0.0, 0.0]
      high: [17.5, 55.0, 0.01]
    observation:
      low: [0.0, 0.0, 0.0]
      high: [4095.0, 10230.0, 4095.0]
    reward:
      low: [0.0]
      high: [4095.0]

  mass: 1.0 # TODO: Убрать после решения проблемы с двойным созданием подключения
  k_linear: 1.0
  k_nonlinear: 1.0
  k_damping: 0.1

  process_noise_std: 0.05
  measurement_noise_std: 0.02

train:
  batch_size: 4
  
  update_to_data: 16
  update_actor_freq: 2 

  total_train_steps: 10_000