defaults:
  - train_async
  - _self_

experiment_name: td3_train_async_simulation

env:
  name: linear  

  time_constant: 0.5
  gain: 1.0
  initial_process_variable: 0.0
  dt: 0.01

  warmup_steps: 200
  pretrain_blocks: 1500 # TODO: рассчитывать через другие параметры
  block_size: 200
  burn_in_steps: 100  
  
  process_variable_max: 10230.0
  control_output_max: 4095.0
  
  default_kp: 0.0
  default_ki: 0.0
  default_kd: 0.0
  
  kp_min: 0.0
  ki_min: 0.0
  kd_min: 0.0
  kp_max: 100.0
  ki_max: 50.0
  kd_max: 0.0

data:
  min_data_for_training: 1000
