# Конфиг для обучения на симуляции
defaults:
  - train_async
  - _self_

experiment_name: td3_train_async_simulation

env:
  name: simulation  # Переключаемся на симуляцию
  
  # Параметры симуляции
  mass: 1.0
  k_linear: 1.0
  k_nonlinear: 1.0
  k_damping: 0.1
  process_noise_std: 0.05
  measurement_noise_std: 0.02
  
  # Параметры обучения
  pretrain_blocks: 100
  burn_in_steps: 20

# Убираем serial конфиг для симуляции
# serial: # Закомментировано, так как не нужно для симуляции
