experiment_name: td3_train_real_async
seed: 42 

defaults:
  - agent: agent
  - _self_

serial: # CHECK
  port: COM3 
  baudrate: 115200
  timeout: 0.1

env:
  setpoint: 1200 # CHECK

  reward:
    name: relative # exponential absolute relative
    args:
      k: 9.0

  frame_skip: 1
  repeat_count: 1

  bounds:
    action:
      low: [0.0, 0.0, 0.0]
      high: [17.5, 55.0, 0.01]
    observation:
      low: [0.0, 0.0, 0.0]
      high: [10230.0, 4095.0, 10230.0]
    reward:
      low: [-10230.0]
      high: [0]

  mass: 1.0 # TODO: Убрать после решения проблемы с двойным созданием подключения
  k_linear: 1.0
  k_nonlinear: 1.0
  k_damping: 0.1

  process_noise_std: 0.05
  measurement_noise_std: 0.02

hydra:
  run:
    dir: experiments/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  frames_per_batch: 100
  total_frames: 1_000_000

  buffer_size: 100_000

train:
  batch_size: 128
  
  update_to_data: 16
  update_actor_freq: 2 

  total_train_steps: 1_000_000_000 # Обучение идет до прерывания через CTRL + C