use_lstm: False

lstm_hidden_size: 32
lstm_num_layers: 1
python_based_lstm_policy: False

mlp_num_cells: [256, 256]

q_lstm_hidden_size: ${agent.lstm_hidden_size}
q_lstm_num_layers: ${agent.lstm_num_layers}
python_based_lstm_qvalue: False

q_mlp_num_cells: ${agent.mlp_num_cells}

policy_noise: 0.2
noise_clip: 0.5

gamma: 0.99
num_qvalue_nets: 2
target_update_eps: 0.95

learning_rate_actor: 1e-3
learning_rate_critic: 1e-3