mlp_num_cells: [256, 256]
q_mlp_num_cells: ${agent.mlp_num_cells}

policy_noise: 0.0
noise_clip: 0.0

gamma: 0.99
num_qvalue_nets: 2
target_update_eps: 0.95

learning_rate_actor: 1e-3
learning_rate_critic: 1e-3